apiVersion: v2
name: observeflow
description: ObserveFlow - Polyglot E-Commerce Microservices Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - e-commerce
  - observability
  - opentelemetry
maintainers:
  - name: Vansh Shah
