server.port=4005
spring.application.name=inventory-service
management.endpoints.web.exposure.include=health
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{trace_id}/%X{span_id}] %-5level %logger{36} - %msg%n
