apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.frontendService.name }}
    {{- include "observeflow.labels" . | nindent 4 }}
spec:
  type: {{ (.Values.frontendService.service).type | default "ClusterIP" }}
  selector:
    app: {{ .Values.frontendService.name }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.port }}
      protocol: TCP
      {{- if and .Values.frontendService.service .Values.frontendService.service.nodePort }}
      nodePort: {{ .Values.frontendService.service.nodePort }}
      {{- end }}
